version: 2
updates:
  # Maintain npm dependencies for JS/CSS and Block assets
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 5

  # Maintain Composer dependencies for PHP and WPCS
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 5

  # Keep GitHub Actions workflows up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"